// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmmyC5t4RKmYpiz376YA-MTBPzj-TH7Mk',
    appId: '1:109397302228:web:da32c574764fd4f9165441',
    messagingSenderId: '109397302228',
    projectId: 'studentrecord-58fef',
    authDomain: 'studentrecord-58fef.firebaseapp.com',
    storageBucket: 'studentrecord-58fef.appspot.com',
    measurementId: 'G-X45XKRC5MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAVEBX-Kzwca-qsZpCEnmmcR81AT_BZfc',
    appId: '1:109397302228:android:3611a02b84da88f4165441',
    messagingSenderId: '109397302228',
    projectId: 'studentrecord-58fef',
    storageBucket: 'studentrecord-58fef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOF666gg_k0oG4RHXdNiDVfQ800bG3rsQ',
    appId: '1:109397302228:ios:1ab4b248948c8e32165441',
    messagingSenderId: '109397302228',
    projectId: 'studentrecord-58fef',
    storageBucket: 'studentrecord-58fef.appspot.com',
    iosBundleId: 'com.sam.studentRecord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOF666gg_k0oG4RHXdNiDVfQ800bG3rsQ',
    appId: '1:109397302228:ios:1ab4b248948c8e32165441',
    messagingSenderId: '109397302228',
    projectId: 'studentrecord-58fef',
    storageBucket: 'studentrecord-58fef.appspot.com',
    iosBundleId: 'com.sam.studentRecord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmmyC5t4RKmYpiz376YA-MTBPzj-TH7Mk',
    appId: '1:109397302228:web:e85305ee19f79c98165441',
    messagingSenderId: '109397302228',
    projectId: 'studentrecord-58fef',
    authDomain: 'studentrecord-58fef.firebaseapp.com',
    storageBucket: 'studentrecord-58fef.appspot.com',
    measurementId: 'G-Y6R67QH905',
  );
}
